### ISSUE TITLE
Validator not validating incomplete state pointset

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#193]
Using the validator, the state_pointset does not raise an error if there are missing points. Conversely the validator correctly identifies missing points from the event_pointset

Example below, can be tested by adding points to the metadata for the pubber device
```
Processing device #1/12: AHU-9/state_pointset
Warning: Nashorn engine is planned to be removed from a future JDK release
Validation complete AHU-9/state_pointset
Processing device #1/12: AHU-9/state_system
Validation complete AHU-9/state_system
Processng device #2/12: AHU-9/event_pointset
java.lang.RuntimeException: Metadata validation failed: Missing points: missing_point
	at com.google.daq.mqtt.validator.ReportingDevice.validateMetadata(ReportingDevice.java:67)
	at com.google.daq.mqtt.validator.Validator.validateUpdate(Validator.java:381)
	at com.google.daq.mqtt.validator.Validator.validateMessage(Validator.java:286)
	at com.google.daq.mqtt.validator.Validator.lambda$messageValidator$0(Validator.java:233)
	at com.google.daq.mqtt.util.PubSubClient.processMessage(PubSubClient.java:112)
	at com.google.daq.mqtt.validator.Validator.messageLoop(Validator.java:261)
	at com.google.daq.mqtt.validator.Validator.validatePubSub(Validator.java:239)
	at com.google.daq.mqtt.validator.Validator.main(Validator.java:124)
Processing device #2/12: AHU-9/event_system

```

**Comment by grafnu** [comment]
Should be fixed now: https://github.com/faucetsdn/udmi/pull/356
