### ISSUE TITLE
Validator not working after subType introduction

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#270]
Running the validator using a **pub/sub subscription**, I receive the following errors. Cloud functions have been updated to the latest versions

With event messages:
  ```
1 schema violations found
    object has missing required properties (["subType"])
```

With state messages:
`java.lang.RuntimeException: Malformed plural subType state`

**Comment by noursaidi** [comment]
Validating with the reflector rather than pubsub (validator/bin/validate daq1-273309 schema reflect AHU-9 ~/nes-site-model)

```
java.lang.RuntimeException: Malformed plural subType update
	at com.google.daq.mqtt.validator.Validator.makeSchemaName(Validator.java:459)
	at com.google.daq.mqtt.validator.Validator.validateUpdate(Validator.java:318)
	at com.google.daq.mqtt.validator.Validator.validateMessage(Validator.java:286)
	at com.google.daq.mqtt.validator.Validator.lambda$messageValidator$0(Validator.java:233)
	at com.google.bos.iot.core.proxy.IotCoreClient.processMessage(IotCoreClient.java:127)
	at com.google.daq.mqtt.validator.Validator.messageLoop(Validator.java:261)
	at com.google.daq.mqtt.validator.Validator.validateReflector(Validator.java:247)
	at com.google.daq.mqtt.validator.Validator.main(Validator.java:130)
java.lang.RuntimeException: Malformed plural subType state
	at com.google.daq.mqtt.validator.Validator.makeSchemaName(Validator.java:459)
	at com.google.daq.mqtt.validator.Validator.validateUpdate(Validator.java:318)
	at com.google.daq.mqtt.validator.Validator.validateMessage(Validator.java:286)
	at com.google.daq.mqtt.validator.Validator.lambda$messageValidator$0(Validator.java:233)
	at com.google.bos.iot.core.proxy.IotCoreClient.processMessage(IotCoreClient.java:127)
	at com.google.daq.mqtt.validator.Validator.messageLoop(Validator.java:261)
	at com.google.daq.mqtt.validator.Validator.validateReflector(Validator.java:247)
	at com.google.daq.mqtt.validator.Validator.main(Validator.java:130)
java.lang.RuntimeException: Malformed plural subType state
	at com.google.daq.mqtt.validator.Validator.makeSchemaName(Validator.java:459)
	at com.google.daq.mqtt.validator.Validator.validateUpdate(Validator.java:318)
	at com.google.daq.mqtt.validator.Validator.validateMessage(Validator.java:286)
	at com.google.daq.mqtt.validator.Validator.lambda$messageValidator$0(Validator.java:233)
	at com.google.bos.iot.core.proxy.IotCoreClient.processMessage(IotCoreClient.java:127)
	at com.google.daq.mqtt.validator.Validator.messageLoop(Validator.java:261)
	at com.google.daq.mqtt.validator.Validator.validateReflector(Validator.java:247)
	at com.google.daq.mqtt.validator.Validator.main(Validator.java:130)
java.lang.RuntimeException: Malformed plural subType event
	at com.google.daq.mqtt.validator.Validator.makeSchemaName(Validator.java:459)
	at com.google.daq.mqtt.validator.Validator.validateUpdate(Validator.java:318)
	at com.google.daq.mqtt.validator.Validator.validateMessage(Validator.java:286)
	at com.google.daq.mqtt.validator.Validator.lambda$messageValidator$0(Validator.java:233)
	at com.google.bos.iot.core.proxy.IotCoreClient.processMessage(IotCoreClient.java:127)
	at com.google.daq.mqtt.validator.Validator.messageLoop(Validator.java:261)
	at com.google.daq.mqtt.validator.Validator.validateReflector(Validator.java:247)
	at com.google.daq.mqtt.validator.Validator.main(Validator.java:130)
java.lang.RuntimeException: Malformed plural subType event
	at com.google.daq.mqtt.validator.Validator.makeSchemaName(Validator.java:459)
	at com.google.daq.mqtt.validator.Validator.validateUpdate(Validator.java:318)
	at com.google.daq.mqtt.validator.Validator.validateMessage(Validator.java:286)
	at com.google.daq.mqtt.validator.Validator.lambda$messageValidator$0(Validator.java:233)
	at com.google.bos.iot.core.proxy.IotCoreClient.processMessage(IotCoreClient.java:127)
	at com.google.daq.mqtt.validator.Validator.messageLoop(Validator.java:261)
	at com.google.daq.mqtt.validator.Validator.validateReflector(Validator.
```

**Comment by pisuke** [comment]
I confirm that I am experiencing the same errors using pubber and validator.

**Comment by grafnu** [comment]
Believed to be fixed with PR https://github.com/faucetsdn/udmi/pull/272 -- PTAL
