### ISSUE TITLE
Registrar exits when cloud auth is not set

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#321]
When the `cloud` field is missing, the registrar throws an exception and terminates.

Expected behaviour is to continue and add the error the report output

```
Writing normalized /Users/nournew/udmi_site_model/devices/AHU-1/out/metadata_norm.json
java.lang.RuntimeException: While processing devices
	at com.google.daq.mqtt.registrar.Registrar.processDevices(Registrar.java:290)
	at com.google.daq.mqtt.registrar.Registrar.processDevices(Registrar.java:255)
	at com.google.daq.mqtt.registrar.Registrar.main(Registrar.java:113)
Caused by: java.lang.RuntimeException: While getting settings for device AHU-1
	at com.google.daq.mqtt.registrar.LocalDevice.getSettings(LocalDevice.java:481)
	at com.google.daq.mqtt.registrar.Registrar.lambda$validateKeys$12(Registrar.java:596)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.google.daq.mqtt.registrar.Registrar.validateKeys(Registrar.java:594)
	at com.google.daq.mqtt.registrar.Registrar.loadLocalDevices(Registrar.java:554)
	at com.google.daq.mqtt.registrar.Registrar.processDevices(Registrar.java:263)
	... 2 more
Caused by: java.lang.RuntimeException: Invalid auth type null
	at com.google.daq.mqtt.registrar.LocalDevice.getKeyBytes(LocalDevice.java:491)
	at com.google.daq.mqtt.registrar.LocalDevice.getSettings(LocalDevice.java:477)
	... 15 more
Exception in thread "main" java.lang.RuntimeException: main exception
	at com.google.daq.mqtt.registrar.Registrar.main(Registrar.java:125)
Caused by: java.lang.RuntimeException: While processing devices
	at com.google.daq.mqtt.registrar.Registrar.processDevices(Registrar.java:290)
	at com.google.daq.mqtt.registrar.Registrar.processDevices(Registrar.java:255)
	at com.google.daq.mqtt.registrar.Registrar.main(Registrar.java:113)
Caused by: java.lang.RuntimeException: While getting settings for device AHU-1
	at com.google.daq.mqtt.registrar.LocalDevice.getSettings(LocalDevice.java:481)
	at com.google.daq.mqtt.registrar.Registrar.lambda$validateKeys$12(Registrar.java:596)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.google.daq.mqtt.registrar.Registrar.validateKeys(Registrar.java:594)
	at com.google.daq.mqtt.registrar.Registrar.loadLocalDevices(Registrar.java:554)
	at com.google.daq.mqtt.registrar.Registrar.processDevices(Registrar.java:263)
	... 2 more
Caused by: java.lang.RuntimeException: Invalid auth type null
	at com.google.daq.mqtt.registrar.LocalDevice.getKeyBytes(LocalDevice.java:491)
	at com.google.daq.mqtt.registrar.LocalDevice.getSettings(LocalDevice.java:477)
	... 15 more

```

Steps to recreate.
1. Download UDMI example repo https://github.com/faucetsdn/udmi_site_model.git
2. Delete the entire cloud block from one of the devices
3. Run the registar tool without specifying a GCP project for local validation

**Comment by noursaidi** [comment]
Issue no longer occurs
