### ISSUE TITLE
Pubber won't run if any device metadata in the site model has an error

### ISSUE THREAD

**Issue by noursaidi** [faucetsdn/udmi#344]
Running pubber as AHU-1, but device SNS-4 has an error in the metadata (an additional field)
```
nournew@macbook-2 udmi %  bin/pubber ~/udmi_site_model project_id AHU-1 567
Building pubber...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Running tools version 1.3.12-93-g836d49a1
Exception in thread "main" java.lang.RuntimeException: While reading metadata file /Users/nournew/udmi_site_model/devices/SNS-4/metadata.json
	at daq.pubber.Pubber.getDeviceMetadata(Pubber.java:278)
	at daq.pubber.Pubber.lambda$loadDeviceMetadata$3(Pubber.java:265)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at daq.pubber.Pubber.loadDeviceMetadata(Pubber.java:265)
	at daq.pubber.Pubber.initializeDevice(Pubber.java:344)
	at daq.pubber.Pubber.initialize(Pubber.java:511)
	at daq.pubber.Pubber.singularPubber(Pubber.java:214)
	at daq.pubber.Pubber.main(Pubber.java:199)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "systemdsa" (class udmi.schema.Metadata), not marked as ignorable (11 known properties: "discovery", "localnet", "gateway", "cloud", "timestamp", "version", "description", "hash", "system", "testing", "pointset"])
 at [Source: (File); line: 12, column: 17] (through reference chain: udmi.schema.Metadata["systemdsa"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413)
	at daq.pubber.Pubber.getDeviceMetadata(Pubber.java:275)
	... 14 more
nournew@macbook-2 udmi % 

```

**Comment by noursaidi** [comment]
Fixed in #600
