### ISSUE TITLE
validator JWT token expired

### ISSUE THREAD

**Issue by pisuke** [faucetsdn/udmi#380]
I've attempted doing a long validator run on a IoT Core registry that has more than 10k devices, but unfortunately the process stops with the following output:

```
[MQTT Rec: projects/someproject/locations/us-central1/registries/UDMS-REFLECT/devices/SOME-REGISTRY] WARN com.google.bos.iot.core.proxy.MqttPublisher - MQTT connection lost SOME-REGISTRY
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
mqtt client error: Connection lost
```

After a little bit more investigations, on IoT Core this error status is recorded

```
[16] mqtt: SERVER: The authorization token expired.
```

Perhaps validator doesn't refresh the JWT token?

**Comment by grafnu** [comment]
Can confirm... The relevant function is maybeRefreshJwt in
MqttPublisher,java that is currently only called when sending a message --
but the validator is just listening a lot, never sends, The fix should
(fingers crossed) be relatively easy...
